### PR TITLE
Structural fixes to vsso-core

### PR DESCRIPTION
**Pull request by jdacoello**
This PR fixes the following structural issues in the `vsso-core` model:

**fix**: Add the union in the domain of `positionedAt` according to its definition.
**fix**: Remove `partOfVehicle` object property (issue #31)
**feat**: Add Transitive characteristic to `partOf` property (issue #31)
**fix**: Remove redundant object properties `hasStaticVehicleProperty` and `hasDynamicVehicleProperty`. Add object property `hasVehicleProperty` (issue #30)
**feat**: Add disjoint (i.e., no individual can be an instance of more than one of the primitive classes)
**fix**: Change namespace from github.com to the official w3.org domain (complements the solution to #25 for `vsso-core`)

This cleaner version of `vsso-core` looks like the following:

image

### CODE REVIEW

**Comment by felix-loesch** [comment]
OK for me. The object property vsso:partOf in your fix has still the old rdfs:comment and rdfs:label. Instead of "partOfVehicleComponent" it should be named "partOf" to be consistent with the IRI definition.

**Comment by jdacoello** [comment]
> The object property vsso:partOf in your fix has still the old rdfs:comment and rdfs:label. Instead of "partOfVehicleComponent" it should be named "partOf" to be consistent with the IRI definition.

Done! I committed the fixed annotation properties.

**Comment by jdacoello** [comment]
FYI the resulting vsso-core model looks like:

image

**Comment by danielwilms** [comment]
A couple of things:
First of all this PR addresses many different aspects and makes the discussion really hard and long. Second, none of the points has been discussed initially. So, I'd suggest the following:

1. Let's close this PR
2. Create issues for the changes you propose, which are independent of each other
3. Once they are concluded you can create PRs.

Some of the commits have side effects to the generation, and we should go through a thorough discussion.

**Comment by jdacoello** [comment]
This PR is has been closed because, as suggested, it will be divided into individual issues to facilitate discussions and decisions.

**Pull request closed without merging**
